filter:
    excluded_paths:
        - _includes/theme/*
        - classes/DomainMOD/AboveCom.php
        - classes/DomainMOD/DomainQueue.php
        - classes/DomainMOD/DreamHost.php
        - classes/DomainMOD/DwAccounts.php
        - classes/DomainMOD/DwRecords.php
        - classes/DomainMOD/Layout.php
        - classes/DomainMOD/OpenSrs.php
        - classes/DomainMOD/Page.php
        - vendor/*
